server:
  port: 8080
  context-path: /sell
#spring.jpa.properties.hibernate.show_sql=true         
#spring.jpa.properties.hibernate.format_sql=true      
#spring.jpa.properties.hibernate.use_sql_comments=true

spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        show_sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&useSSL=false
    username: root
    password: 3770662Hg!@
  mvc:
    view:
      suffix: .html

wechat:
  appId: 12345
  appSecret: 54321




#logging:
#  file: /var/log/tomcat/sell.log
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
